# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(976, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.slider_time = QtWidgets.QSlider(self.centralwidget)
        self.slider_time.setGeometry(QtCore.QRect(10, 600, 671, 20))
        self.slider_time.setOrientation(QtCore.Qt.Horizontal)
        self.slider_time.setObjectName("slider_time")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(880, 580, 88, 34))
        self.btn_stop.setObjectName("btn_stop")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(780, 580, 88, 34))
        self.btn_play.setObjectName("btn_play")
        self.lv_files = QtWidgets.QListView(self.centralwidget)
        self.lv_files.setGeometry(QtCore.QRect(10, 40, 351, 551))
        self.lv_files.setObjectName("lv_files")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(710, 600, 58, 18))
        self.label_time.setObjectName("label_time")
        self.lv_text = QtWidgets.QListView(self.centralwidget)
        self.lv_text.setGeometry(QtCore.QRect(690, 310, 121, 251))
        self.lv_text.setObjectName("lv_text")
        self.lv_stops = QtWidgets.QListView(self.centralwidget)
        self.lv_stops.setGeometry(QtCore.QRect(410, 310, 91, 281))
        self.lv_stops.setObjectName("lv_stops")
        self.text_stop_time = QtWidgets.QTextEdit(self.centralwidget)
        self.text_stop_time.setGeometry(QtCore.QRect(520, 310, 81, 41))
        self.text_stop_time.setObjectName("text_stop_time")
        self.btn_test_point = QtWidgets.QPushButton(self.centralwidget)
        self.btn_test_point.setGeometry(QtCore.QRect(520, 370, 88, 34))
        self.btn_test_point.setObjectName("btn_test_point")
        self.btn_add_stop_point = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_stop_point.setGeometry(QtCore.QRect(520, 420, 88, 34))
        self.btn_add_stop_point.setObjectName("btn_add_stop_point")
        self.btn_remove_stop_point = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remove_stop_point.setGeometry(QtCore.QRect(520, 460, 88, 34))
        self.btn_remove_stop_point.setObjectName("btn_remove_stop_point")
        self.text_time_text = QtWidgets.QTextEdit(self.centralwidget)
        self.text_time_text.setGeometry(QtCore.QRect(690, 20, 81, 41))
        self.text_time_text.setObjectName("text_time_text")
        self.text_text_text = QtWidgets.QTextEdit(self.centralwidget)
        self.text_text_text.setGeometry(QtCore.QRect(690, 80, 281, 201))
        self.text_text_text.setObjectName("text_text_text")
        self.btn_add_text = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_text.setGeometry(QtCore.QRect(840, 310, 88, 34))
        self.btn_add_text.setObjectName("btn_add_text")
        self.btn_remove_text = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remove_text.setGeometry(QtCore.QRect(840, 360, 88, 34))
        self.btn_remove_text.setObjectName("btn_remove_text")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(10, 0, 88, 34))
        self.btn_open.setObjectName("btn_open")
        self.text_title = QtWidgets.QTextEdit(self.centralwidget)
        self.text_title.setGeometry(QtCore.QRect(400, 80, 271, 31))
        self.text_title.setObjectName("text_title")
        self.text_album = QtWidgets.QTextEdit(self.centralwidget)
        self.text_album.setGeometry(QtCore.QRect(400, 190, 271, 31))
        self.text_album.setObjectName("text_album")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(400, 60, 58, 18))
        self.label_title.setObjectName("label_title")
        self.label_album = QtWidgets.QLabel(self.centralwidget)
        self.label_album.setGeometry(QtCore.QRect(410, 170, 58, 18))
        self.label_album.setObjectName("label_album")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(120, 0, 88, 34))
        self.btn_save.setObjectName("btn_save")

        self.label_number = QtWidgets.QLabel(self.centralwidget)
        self.label_number.setGeometry(QtCore.QRect(450, 10, 88, 34))
        self.label_number.setObjectName("lv_number")

        self.text_number = QtWidgets.QTextEdit(self.centralwidget)
        self.text_number.setGeometry(QtCore.QRect(500, 10, 88, 34))
        self.text_number.setObjectName("text_number")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_play.setText(_translate("MainWindow", "play/pause"))
        self.label_time.setText(_translate("MainWindow", "0:00"))
        self.btn_test_point.setText(_translate("MainWindow", "Test"))
        self.btn_add_stop_point.setText(_translate("MainWindow", "Add"))
        self.btn_remove_stop_point.setText(_translate("MainWindow", "Remove"))
        self.btn_add_text.setText(_translate("MainWindow", "Add"))
        self.btn_remove_text.setText(_translate("MainWindow", "Remove"))
        self.btn_open.setText(_translate("MainWindow", "Open"))
        self.label_title.setText(_translate("MainWindow", "Title"))
        self.label_number.setText(_translate("MainWindow", "Numer"))
        self.label_album.setText(_translate("MainWindow", "Album"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
